# Será neecsario ajustar las composiciones en función del entorno
# https://docs.docker.com/compose/production/

# Queda pendiente uniformar el versionado de las imágenes

version: "3" # Versión de Docker Compose
services:
    bot:
        container_name: helpbot_beta
        # restart: always # Si el contenedor falla, lo reinicia (sólo debería usarse en producción)
        image: easyxploit/helpbot
        build: .
        links:
            - mongodb
        volumes:
            - .:/usr/src/helpbot # Para poder modificar el código en ejecución con Nodemon
    mongodb:
            container_name: mongodb
            image: mongo:6.0
            # environment: # No parece necesario, dado que se crea mediante un script
                # - MONGO_INITDB_DATABASE=demo_database
                # - MONGO_INITDB_ROOT_USERNAME=demo_user
                # - MONGO_INITDB_ROOT_PASSWORD=demo_password
            # command: mongod --quiet --logpath /dev/null  # No funciona (buscar alternativa para ofuscar los logs de MongoDB)
            volumes:
                - /data/db # Si no hay parte anterior a los :, quiere decir que se usa un directorio anónimo del host
            ports:
            - '27020:27017' # Puertos: externo:interno
